Remove scsi files
ostis-ai/ims.ostis.kb pull request #15
Opened 2023-02-09 13:34 UTC by SHtress

2023-02-13 15:53 UTC, KovalM requested changes
.scsi files should be .scs files with next logic

scs content:

```
countour_name = [*
//scsi content
*];;
```

2023-02-22 08:20 UTC, KovalM requested changes

2023-02-22 08:20 UTC, KovalM commented on ims/OSTIS_hist_curr_stt_perspect_of_evol_and_use/section_structure_project_OSTIS/section_structure_project_OSTIS_content.scs
> +section_structure_project_OSTIS =  [*project_ostis
```suggestion
section_structure_project_OSTIS =  [*
project_ostis
```

2023-02-22 13:25 UTC, KovalM approved these changes

2023-02-22 13:56 UTC, ShunkevichDV approved these changes

2023-02-22 13:58 UTC, merged