Add SD of users
ostis-ai/ims.ostis.kb pull request #3
Opened 2022-04-01 15:51 UTC by KsenBantsevich

2022-04-01 18:13 UTC, KovalM requested changes

2022-04-01 18:13 UTC, KovalM commented on ims/ostis_tech/lib_ostis/section_library_of_reusable_components_kb/section_subject_domain_of_users/concepts/concept_user.scs
> +    [пользователь]
Fix formatting

2022-04-01 18:13 UTC, KovalM commented on ims/ostis_tech/lib_ostis/section_library_of_reusable_components_kb/section_subject_domain_of_users/concepts/concept_user.scs
> +		...
What about constants?

2022-04-01 18:13 UTC, KovalM commented on ims/ostis_tech/lib_ostis/section_library_of_reusable_components_kb/section_subject_domain_of_users/relations/nrel_login.scs
> +=> nrel_second_domain: concept_token;
What is concept_token?

2022-04-01 18:13 UTC, KovalM commented on ims/ostis_tech/lib_ostis/section_library_of_reusable_components_kb/section_subject_domain_of_users/relations/nrel_login.scs
> +			[]
Add English

2022-04-01 18:13 UTC, KovalM commented on ims/ostis_tech/lib_ostis/section_library_of_reusable_components_kb/section_subject_domain_of_users/relations/nrel_user_used_language.scs
> +        languages
fix formatting, add binary_relation constant

2022-04-01 18:13 UTC, KovalM commented on ims/ostis_tech/lib_ostis/section_library_of_reusable_components_kb/section_subject_domain_of_users/relations/nrel_user_used_language.scs
> +			[]
Add English translate

2022-04-01 18:13 UTC, KovalM commented on ims/ostis_tech/lib_ostis/section_library_of_reusable_components_kb/section_subject_domain_of_users/section_subject_domain_of_users .scs
> +section_subject_domain_of_users
I think we can use already exist SD subject_domain_developers_actions_knowledge_base_cooperation_hierarchy. We will discuss about using current state of this SD for our propose. And let's discuss @ShunkevichDV why know we use users roles as norole relation?

2022-04-04 10:12 UTC, ShunkevichDV requested changes

2022-04-04 10:12 UTC, ShunkevichDV commented on ims/ostis_tech/lib_ostis/section_library_of_reusable_components_kb/section_subject_domain_of_users/relations/nrel_language_used_by_the_user.scs
> +			[Используемый пользователем язык* - бинарное отношение, связывающее пользователя и язык, который он использует для общения.]
For communication with who?
In different systems user can use different languages, we should say about it, this language is only for this system

2022-04-04 10:12 UTC, ShunkevichDV commented on ims/ostis_tech/lib_ostis/section_library_of_reusable_components_kb/section_subject_domain_of_users/relations/nrel_language_used_by_the_user.scs
> +			[Language used by the user* is a binary relation that connects the user and the language that they use to communicate.]
Why *they*?

2022-04-04 10:12 UTC, ShunkevichDV commented on ims/ostis_tech/lib_ostis/section_library_of_reusable_components_kb/section_subject_domain_of_users/relations/nrel_login.scs
> +			[Логин* - бинарное отношение, связывающее пользователя и уникальную строку, предназначенную для авторизации в системе.]
unique within what scope?

2022-04-04 12:15 UTC, ShunkevichDV approved these changes

2022-04-04 12:20 UTC, KovalM approved these changes

2022-04-05 07:45 UTC, merged