refactor: harmonize role relations for scp-operands
ostis-ai/ims.ostis.kb pull request #44
Opened 2024-12-02 23:35 UTC by NikitaZotov

2024-12-04 09:22 UTC, kilativ-dotcom requested changes

2024-12-04 09:22 UTC, kilativ-dotcom commented on ims/ostis_tech/lib_ostis/sectn_lib_of_reusable_comp_ui/ui_menu/eekb_commands/kb_verification_for_eekb/lib_ui_menu_kb_verification_for_eekb.scs
> +		lib_component_ui_menu_file_for_agent_of_checking_subject_domain_membership_for_classes_in_given_structure;
if you want to fix access->membreship then there are some left
![image](https://github.com/user-attachments/assets/ad498775-2450-4448-a30c-4b587d0760f1)

2024-12-04 09:22 UTC, kilativ-dotcom commented on ims/ostis_tech/lib_ostis/sectn_lib_reusable_comp_kpm/reusable_sc_agents/lib_scp_agents/Methods_evaluation/Depth_metrics/common/scp_prog_comp/lib_comp_find_all_start_vertexes/proc_find_all_start_v_content.scs
> +		_-> rrel_4:: rrel_assign:: rrel_common_arc:: rrel_const_perm_pos_arc:: rrel_scp_var:: _arc1;;
probably rrel_2 should be common and rrel_4 membership

2024-12-04 09:22 UTC, kilativ-dotcom commented on ims/ostis_tech/lib_ostis/sectn_lib_reusable_comp_kpm/reusable_sc_agents/lib_scp_agents/Methods_evaluation/Depth_metrics/common/scp_prog_comp/lib_comp_find_all_start_vertexes/proc_find_all_start_v_content.scs
> +		_-> rrel_4:: rrel_assign:: rrel_common_arc:: rrel_const_perm_pos_arc:: rrel_scp_var:: _arc1;;
same

2024-12-04 09:22 UTC, kilativ-dotcom commented on ims/ostis_tech/lib_ostis/sectn_lib_reusable_comp_kpm/reusable_sc_agents/lib_scp_agents/search/find_definitional_domain/agent_of_finding_definitional_domain_content.scs
> +		_-> rrel_4:: rrel_assign:: rrel_common_arc:: rrel_const_perm_pos_arc:: rrel_scp_var:: _arc1;;
same

2024-12-04 09:22 UTC, kilativ-dotcom commented on ims/ostis_tech/lib_ostis/sectn_lib_reusable_comp_kpm/reusable_sc_agents/lib_scp_agents/verification/agent_check_cycle_exist_order_rel/agent_check_cycle_exist_order_rel_content.scs
> +		_-> rrel_3:: rrel_assign:: rrel_common_arc:: rrel_const_perm_pos_arc:: rrel_scp_var:: _arc1;;
same

2024-12-04 09:22 UTC, kilativ-dotcom commented on ims/ostis_tech/lib_ostis/sectn_lib_reusable_comp_kpm/reusable_sc_agents/lib_scp_agents/verification/agent_check_cycle_exist_order_rel/agent_check_cycle_exist_order_rel_content.scs
> +		_-> rrel_3:: rrel_assign:: rrel_common_arc:: rrel_const_perm_pos_arc:: rrel_scp_var:: _arc1;;
same

2024-12-04 09:22 UTC, kilativ-dotcom commented on ims/ostis_tech/semantic_network_represent/section_scs_code/scs_code_dividers/section_scs_code_additional_connectors/section_scs_code_additional_connectors.scs
> +		=> nrel_key_sc_element_order: (section_scs_code_additional_connectors -> scs_divider_var_pos_stat_membership_arc)
should also stat be replaced with perm and nonstat replaced with temp?

2024-12-04 09:22 UTC, kilativ-dotcom commented on ims/ostis_tech/semantic_network_represent/section_scs_code/scs_code_dividers/section_scs_code_additional_connectors/section_scs_code_additional_connectors.scs
> +		=> nrel_key_sc_element_order: (section_scs_code_additional_connectors -> scs_divider_const_fuz_nonstat_membership_arc)
some of fuz subtypes don't exist anymore

2024-12-04 09:22 UTC, kilativ-dotcom commented on ims/ostis_tech/semantic_network_represent/section_scs_code/scs_code_dividers/section_scs_code_additional_connectors/section_scs_code_additional_connectors_content.scs
>  	"file://img/var_pos_stat_acc_scs_editor1.png" (* => nrel_format: format_png;; *);
images have 'acc' in their names, which is shortened 'accessory'

2024-12-04 09:22 UTC, kilativ-dotcom commented on ims/ostis_tech/semantic_networks_processing/section_basic_programming_language_scp/section_basic_programming_language_scp_content.scs
>  	<= nrel_subdividing:
this shouldn't be a subdividing, it is possible that arc will be a membership arc, but without positivity specified

2024-12-05 23:47 UTC, NikitaZotov commented on ims/ostis_tech/semantic_network_represent/section_scs_code/scs_code_dividers/section_scs_code_additional_connectors/section_scs_code_additional_connectors.scs
> +		=> nrel_key_sc_element_order: (section_scs_code_additional_connectors -> scs_divider_var_pos_stat_membership_arc)
I propose not to change anything in this file, we will change not here, but in the standard.

2024-12-05 23:47 UTC, NikitaZotov commented on ims/ostis_tech/semantic_network_represent/section_scs_code/scs_code_dividers/section_scs_code_additional_connectors/section_scs_code_additional_connectors.scs
> +		=> nrel_key_sc_element_order: (section_scs_code_additional_connectors -> scs_divider_const_fuz_nonstat_membership_arc)
same

2024-12-05 23:47 UTC, NikitaZotov commented on ims/ostis_tech/semantic_network_represent/section_scs_code/scs_code_dividers/section_scs_code_additional_connectors/section_scs_code_additional_connectors_content.scs
>  	"file://img/var_pos_stat_acc_scs_editor1.png" (* => nrel_format: format_png;; *);
same

2024-12-05 23:47 UTC, NikitaZotov commented on ims/ostis_tech/semantic_networks_processing/section_basic_programming_language_scp/section_basic_programming_language_scp_content.scs
>  	<= nrel_subdividing:
same

2024-12-06 08:31 UTC, kilativ-dotcom commented on ims/ostis_tech/semantic_networks_processing/section_basic_programming_language_scp/section_basic_programming_language_scp_content.scs
>  	<= nrel_subdividing:
ok, turns out this file has several 'access sc-arc' mentions

2024-12-06 08:32 UTC, kilativ-dotcom commented on ims/ostis_tech/lib_ostis/sectn_lib_of_reusable_comp_ui/ui_menu/eekb_commands/kb_verification_for_eekb/lib_ui_menu_kb_verification_for_eekb.scs
> +		lib_component_ui_menu_file_for_agent_of_checking_subject_domain_membership_for_classes_in_given_structure;
some are left
![image](https://github.com/user-attachments/assets/80042a52-db5a-4819-9427-960ae41ebc86)

2024-12-06 08:33 UTC, kilativ-dotcom requested changes
left some comments in threads

2025-01-24 09:34 UTC, kilativ-dotcom requested changes
also some accesses are still left
![image](https://github.com/user-attachments/assets/8bd5cde8-f3ce-4acc-86fd-da77fa7b7978)

2025-01-24 09:34 UTC, kilativ-dotcom commented on ims/ostis_tech/unificated_models/section_unificated_models_kb/section_subjdomain_semantic_neighborhoods/nl_files/semantic_neighborhood_by_incoming_arcs_access.html
file should have access in its name

2025-01-24 09:34 UTC, kilativ-dotcom commented on ims/ostis_tech/unificated_models/section_unificated_models_kb/section_subjdomain_semantic_neighborhoods/nl_files/semantic_neighborhood_by_outgoing_arcs_access.html
same

2025-01-24 13:05 UTC, kilativ-dotcom requested changes

2025-01-24 13:05 UTC, kilativ-dotcom commented on ims/ostis_tech/semantic_network_represent/section_scs_code/section_scs_code_scsi/scs_code_htmls/scs_code_core.html
> +&lt;&quot; <b>тип элемента</b> &quot;&gt; ::= (&quot; sc_node || sc_node_link || sc_common_arc || sc_common_edge || sc_main_arc || sc_membership_arc &quot;)<br>
if you decided to change sc_link, sc_arc_common and others then change them everywhere

2025-01-27 08:25 UTC, kilativ-dotcom requested changes

2025-01-27 08:25 UTC, kilativ-dotcom commented on ims/ostis_tech/semantic_network_represent/section_sc_code/section_subjdomain_entities/section_subjdomain_entities_content.scs
>  	sc_edge;
what about this?
more sc-edges are left

2025-01-27 08:25 UTC, kilativ-dotcom commented on ims/ostis_tech/unificated_models/section_unificated_models_kpm/section_subject_domain_of_situations_and_events/content_html/introduction_for_subject_domain_of_situations_and_events_in_sc_memory.html
> +	<li>к изменению состояния актуальных (логически не удаленных <sc_element sys_idtf = "sc_element">sc-элементов</sc_element>) – <sc_element sys_idtf = "sc_node">sc-узел</sc_element> может превратиться
how is this possible? sc-node becoming sc-edge?

2025-01-27 08:48 UTC, NikitaZotov commented on ims/ostis_tech/unificated_models/section_unificated_models_kpm/section_subject_domain_of_situations_and_events/content_html/introduction_for_subject_domain_of_situations_and_events_in_sc_memory.html
> +	<li>к изменению состояния актуальных (логически не удаленных <sc_element sys_idtf = "sc_element">sc-элементов</sc_element>) – <sc_element sys_idtf = "sc_node">sc-узел</sc_element> может превратиться
I don't know. I don't think that's true now. I hadn't seen it in the Standard

2025-01-27 13:05 UTC, kilativ-dotcom approved these changes

2025-01-28 15:27 UTC, merged